targets:
  $default:
    builders:
      hetu_script_generator|bindings:
        generate_for:
          - lib/**.dart

builders:
  bindings:
    import: "package:hetu_script_generator/builder.dart"
    builder_factories: ["bindingsBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["source_gen:combining_builder"]
